run:
  timeout: 1m
  tests: false
  go: '1.20'

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - nilerr
    - unconvert
